---
title: null
---

# Anwendungen von Matrixoperationen in der Bildverarbeitung

Matrizen spielen in der digitalen Bildverarbeitung eine zentrale Rolle, da Bilder mathematisch als Matrizen von Pixelwerten dargestellt werden können.

Matrixoperationen ermöglichen es, Bilder zu analysieren, zu verändern und bestimmte Strukturen hervorzuheben.

Typische Anwendungen sind beispielsweise:

- Filterung von Bildern,
- Reduktion von Bildrauschen,
- Weichzeichnen,
- Bildschärfung,
- Kantenerkennung,
- Transformation von Farb- und Helligkeitswerten.

Ein wichtiges Beispiel ist die **Kantenerkennung mit dem Sobel-Filter**.

> **Hinweis:** Beim Sobel-Filter wird nicht die gewöhnliche Matrixmultiplikation $AB$ verwendet. Der Filter wird lokal elementweise mit einem Bildausschnitt multipliziert. Anschließend werden die entstandenen Werte addiert. Dieses Verfahren ist Bestandteil einer diskreten Filteroperation.

### Ein Bild als Matrix

Ein Graustufenbild kann als Matrix dargestellt werden. Jeder Eintrag der Matrix beschreibt dabei die Intensität eines Pixels.

Typischerweise liegen die Werte zwischen

$$
0
\qquad\text{und}\qquad
255.
$$

Dabei bedeutet:

- $0$: Schwarz
- $255$: Weiß
- Werte zwischen $0$ und $255$: unterschiedliche Graustufen

Betrachten wir beispielsweise die Matrix

$$
A=
\begin{pmatrix}
0 & 51 & 102 & 153 & 204\\
51 & 102 & 153 & 204 & 255\\
102 & 153 & 204 & 255 & 204\\
153 & 204 & 255 & 204 & 153\\
204 & 255 & 204 & 153 & 102
\end{pmatrix}.
$$

Diese Matrix kann direkt als ein Graustufenbild interpretiert werden.

Jedes Matrixelement

$$
a_{ij}
$$

entspricht dabei einem einzelnen Pixel des Bildes.

### Kantenerkennung mit dem Sobel-Filter

Ein häufig verwendetes Verfahren zur Kantenerkennung ist der **Sobel-Filter**.

Dabei werden zwei Filtermatrizen verwendet.

Für Änderungen in $x$-Richtung:

$$
S_x=
\begin{pmatrix}
-1 & 0 & 1\\
-2 & 0 & 2\\
-1 & 0 & 1
\end{pmatrix}.
$$

Für Änderungen in $y$-Richtung:

$$
S_y=
\begin{pmatrix}
-1 & -2 & -1\\
0 & 0 & 0\\
1 & 2 & 1
\end{pmatrix}.
$$

Die beiden Filter reagieren auf Änderungen der Helligkeitswerte in unterschiedlichen Richtungen.

Der Filter $S_x$ erfasst Änderungen in $x$-Richtung und der Filter $S_y$ Änderungen in $y$-Richtung.

Große Änderungen der Pixelintensität weisen auf eine mögliche **Kante im Bild** hin.

Für einen lokalen $3\times3$-Bildausschnitt $R$ wird zunächst elementweise multipliziert:

$$
S_x\circ R,
$$

wobei $\circ$ die Hadamard-Multiplikation bezeichnet.

Anschließend werden alle Elemente der resultierenden Matrix addiert:

$$
G_x
=
\sum_{i=1}^{3}
\sum_{j=1}^{3}
S_x(i,j)R(i,j).
$$

Analog wird

$$
G_y
=
\sum_{i=1}^{3}
\sum_{j=1}^{3}
S_y(i,j)R(i,j)
$$

berechnet.

Die gesamte Kantenstärke kann anschließend durch

$$
G
=
\sqrt{G_x^2+G_y^2}
$$

bestimmt werden.

Je größer $G$ ist, desto stärker ist die erkannte Kante.

### Beispiel: Anwendung des Sobel-Filters

Wir betrachten die folgende Matrix als ein einfaches $7\times7$-Graustufenbild:

$$
A=
\begin{pmatrix}
10&20&30&40&50&60&70\\
15&25&35&45&55&65&75\\
20&30&40&50&60&70&80\\
25&35&45&55&65&75&85\\
30&40&50&60&70&80&90\\
35&45&55&65&75&85&95\\
40&50&60&70&80&90&100
\end{pmatrix}.
$$

Wir betrachten zunächst den oberen linken $3\times3$-Ausschnitt:

$$
R=
\begin{pmatrix}
10&20&30\\
15&25&35\\
20&30&40
\end{pmatrix}.
$$

Auf diesen Bildausschnitt wenden wir den Sobel-Filter

$$
S_x=
\begin{pmatrix}
-1&0&1\\
-2&0&2\\
-1&0&1
\end{pmatrix}
$$

an.

Die elementweise Multiplikation ergibt:

$$
S_x\circ R
=
\begin{pmatrix}
-10&0&30\\
-30&0&70\\
-20&0&40
\end{pmatrix}.
$$

Anschließend werden alle Werte addiert:

$$
G_x
=
-10+0+30-30+0+70-20+0+40.
$$

Damit erhalten wir

$$
\boxed{G_x=80}.
$$

Dieser Wert beschreibt die lokale Intensitätsänderung in $x$-Richtung und wird dem betrachteten Pixel im Ergebnisbild zugeordnet.

In [1]:
import sympy as sp

# 3x3-Bildausschnitt
R = sp.Matrix([
    [10, 20, 30],
    [15, 25, 35],
    [20, 30, 40]
])

# Sobel-Filter in x-Richtung
Sx = sp.Matrix([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
])

# Elementweise Multiplikation
produkt = sp.matrix_multiply_elementwise(Sx, R)

# Summe aller Einträge
Gx = sum(produkt)

print("Bildausschnitt R:")
sp.pprint(R)

print("\nSobel-Filter Sx:")
sp.pprint(Sx)

print("\nElementweise Multiplikation:")
sp.pprint(produkt)

print("\nGx =", Gx)

Bildausschnitt R:
⎡10  20  30⎤
⎢          ⎥
⎢15  25  35⎥
⎢          ⎥
⎣20  30  40⎦

Sobel-Filter Sx:
⎡-1  0  1⎤
⎢        ⎥
⎢-2  0  2⎥
⎢        ⎥
⎣-1  0  1⎦

Elementweise Multiplikation:
⎡-10  0  30⎤
⎢          ⎥
⎢-30  0  70⎥
⎢          ⎥
⎣-20  0  40⎦

Gx = 80


### Anwendung des Filters auf das gesamte Bild

Um das gesamte Bild zu untersuchen, wird der $3\times3$-Sobel-Filter schrittweise über die Bildmatrix bewegt.

Für jede Position wird:

1. ein lokaler $3\times3$-Bildausschnitt ausgewählt,
2. dieser elementweise mit dem Sobel-Filter multipliziert,
3. die Summe der Produkte berechnet,
4. das Ergebnis dem entsprechenden Pixel im Ergebnisbild zugeordnet.

Schematisch:

$$
\text{Bild}
\longrightarrow
\text{$3\times3$-Ausschnitt}
\longrightarrow
\text{Filterung}
\longrightarrow
\text{neuer Pixelwert}.
$$

Anschließend wird der Filter um eine Position verschoben und der Vorgang wiederholt.

Auf diese Weise entsteht aus der ursprünglichen Bildmatrix eine neue Matrix, in der starke Intensitätsänderungen besonders hervorgehoben werden.

### Behandlung der Randpixel

Bei der Anwendung eines $3\times3$-Filters entsteht an den Rändern des Bildes ein Problem.

Für einen Randpixel stehen nicht in allen Richtungen Nachbarpixel zur Verfügung. Deshalb muss festgelegt werden, wie das Bild außerhalb seiner ursprünglichen Grenzen behandelt wird.

Häufig verwendete Methoden sind:

| Methode | Beschreibung |
|---|---|
| **Replicate** | Die äußeren Pixelwerte werden wiederholt. |
| **Symmetric** | Die Werte werden am Bildrand gespiegelt. |
| **Zero-Padding** | Außerhalb des Bildes werden Nullen ergänzt. |
| **Circular** | Das Bild wird behandelt, als würde es sich an den gegenüberliegenden Rändern fortsetzen. |

Die Wahl der Randbehandlung kann das Ergebnis der Filterung beeinflussen.

Für viele Anwendungen wird beispielsweise **Replicate** verwendet, da hierbei die vorhandenen Randwerte fortgesetzt werden.

In [2]:
import numpy as np

A = np.array([
    [10, 20, 30, 40, 50, 60, 70],
    [15, 25, 35, 45, 55, 65, 75],
    [20, 30, 40, 50, 60, 70, 80],
    [25, 35, 45, 55, 65, 75, 85],
    [30, 40, 50, 60, 70, 80, 90],
    [35, 45, 55, 65, 75, 85, 95],
    [40, 50, 60, 70, 80, 90, 100]
], dtype=float)

Sx = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
])

Sy = np.array([
    [-1, -2, -1],
    [0, 0, 0],
    [1, 2, 1]
])

# Randwerte wiederholen (Replicate)
A_pad = np.pad(A, 1, mode="edge")

Gx = np.zeros_like(A)
Gy = np.zeros_like(A)

for i in range(A.shape[0]):
    for j in range(A.shape[1]):

        region = A_pad[i:i+3, j:j+3]

        Gx[i, j] = np.sum(region * Sx)
        Gy[i, j] = np.sum(region * Sy)

# Gesamte Kantenstärke
G = np.sqrt(Gx**2 + Gy**2)

print("Sobel-Ergebnis in x-Richtung:")
print(Gx)

print("\nSobel-Ergebnis in y-Richtung:")
print(Gy)

print("\nKantenstärke:")
print(np.round(G, 2))

Sobel-Ergebnis in x-Richtung:
[[40. 80. 80. 80. 80. 80. 40.]
 [40. 80. 80. 80. 80. 80. 40.]
 [40. 80. 80. 80. 80. 80. 40.]
 [40. 80. 80. 80. 80. 80. 40.]
 [40. 80. 80. 80. 80. 80. 40.]
 [40. 80. 80. 80. 80. 80. 40.]
 [40. 80. 80. 80. 80. 80. 40.]]

Sobel-Ergebnis in y-Richtung:
[[20. 20. 20. 20. 20. 20. 20.]
 [40. 40. 40. 40. 40. 40. 40.]
 [40. 40. 40. 40. 40. 40. 40.]
 [40. 40. 40. 40. 40. 40. 40.]
 [40. 40. 40. 40. 40. 40. 40.]
 [40. 40. 40. 40. 40. 40. 40.]
 [20. 20. 20. 20. 20. 20. 20.]]

Kantenstärke:
[[44.72 82.46 82.46 82.46 82.46 82.46 44.72]
 [56.57 89.44 89.44 89.44 89.44 89.44 56.57]
 [56.57 89.44 89.44 89.44 89.44 89.44 56.57]
 [56.57 89.44 89.44 89.44 89.44 89.44 56.57]
 [56.57 89.44 89.44 89.44 89.44 89.44 56.57]
 [56.57 89.44 89.44 89.44 89.44 89.44 56.57]
 [44.72 82.46 82.46 82.46 82.46 82.46 44.72]]


### Kantenerkennung auf einem synthetischen Bild

Um die Wirkung des Sobel-Filters deutlicher zu erkennen, betrachten wir ein synthetisches $32\times32$-Graustufenbild.

Das Bild besteht aus vier Bereichen mit unterschiedlichen Helligkeitswerten:

$$
A=
\begin{pmatrix}
A_{11} & A_{12}\\
A_{21} & A_{22}
\end{pmatrix},
$$

wobei

$$
A_{11}=10,
\qquad
A_{12}=50,
\qquad
A_{21}=50,
\qquad
A_{22}=90.
$$

Damit entstehen sowohl **vertikale als auch horizontale Helligkeitsänderungen**.

Der Sobel-Filter erkennt diese Übergänge als Kanten.

Der Filter $S_x$ reagiert auf Änderungen in $x$-Richtung, während $S_y$ Änderungen in $y$-Richtung erfasst.

Durch

$$
G=
\sqrt{G_x^2+G_y^2}
$$

werden beide Informationen zu einem gemeinsamen Kantenbild kombiniert.

In [3]:
import numpy as np

# 32x32-Bild aus vier 16x16-Blöcken erzeugen
A11 = np.ones((16, 16)) * 10
A12 = np.ones((16, 16)) * 50
A21 = np.ones((16, 16)) * 50
A22 = np.ones((16, 16)) * 90

bild = np.block([
    [A11, A12],
    [A21, A22]
])

print("Dimension des Bildes:", bild.shape)
print("\nBildmatrix:")
print(bild)

Dimension des Bildes: (32, 32)

Bildmatrix:
[[10. 10. 10. ... 50. 50. 50.]
 [10. 10. 10. ... 50. 50. 50.]
 [10. 10. 10. ... 50. 50. 50.]
 ...
 [50. 50. 50. ... 90. 90. 90.]
 [50. 50. 50. ... 90. 90. 90.]
 [50. 50. 50. ... 90. 90. 90.]]


In [4]:
import numpy as np

Sx = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
])

Sy = np.array([
    [-1, -2, -1],
    [0, 0, 0],
    [1, 2, 1]
])

# Replicate-Randbehandlung
bild_pad = np.pad(bild, 1, mode="edge")

Gx = np.zeros_like(bild)
Gy = np.zeros_like(bild)

for i in range(bild.shape[0]):
    for j in range(bild.shape[1]):

        region = bild_pad[i:i+3, j:j+3]

        Gx[i, j] = np.sum(region * Sx)
        Gy[i, j] = np.sum(region * Sy)

G = np.sqrt(Gx**2 + Gy**2)

print("Maximale Kantenstärke:", G.max())

Maximale Kantenstärke: 226.27416997969522
